apiVersion: apps/v1
kind: Deployment
metadata:
  name: odf-dns
  namespace: openshift-storage
  labels:
    app: odf-dns
spec:
  selector:
    matchLabels:
      app: odf-dns
  template:
    metadata:
      namespace: openshift-storage
      labels:
        app: odf-dns
    spec:
      containers:
        - args:
            - -conf
            - /etc/coredns/Corefile
          command:
            - coredns
          image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3d26faf821ce66d9b25d1c3280ce8b102e4a3935bd2694d77accf7a693fcc3f7
          imagePullPolicy: IfNotPresent
          name: odf-dns
          ports:
            - containerPort: 5353
              name: dns
              protocol: UDP
            - containerPort: 5353
              name: dns-tcp
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 70Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /etc/coredns
              name: config-volume
              readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      preemptionPolicy: PreemptLowerPriority
      priority: 2000001000
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: rook-ceph-system
      serviceAccountName: rook-ceph-system
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            name: odf-dns
          name: config-volume
