apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartcity

resources:
- securitycontextconstraint.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ceph-nano-parameters
    envs:
      - params.env

vars:
  - name: namespace
    objref:
      kind: ConfigMap
      name: ceph-nano-parameters
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace

configurations:
- params.yaml

