apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service-account.yaml
- service.yaml
- statefulset.yaml
- secret-rbac.yaml
- route.yaml

images:
- name: ceph/daemon
  newTag: v0.7
  newName: quay.io/ceph/cn-core
- name: oc
  newName: quay.io/openshift/origin-cli
